---
- name: Provision local development machine
  hosts: localhost
  connection: local
  become: true
  vars_files:
    - ../config/defaults.yaml
  roles:
    - role: common
    - role: dev_shell
    - role: dev
    - role: dotfiles
